### ISSUE TITLE
Release v1.0.0-beta.6

### ISSUE THREAD

**Issue by diafour** [flant/addon-operator#110]
Steps:
- [x] refactor custom metrics to use code from shell-operator https://github.com/flant/shell-operator/pull/165 (done in #112)
- [x] fix tiller error monitoring — sometimes Addon-operator not exits with 1 (done in #113 #114)
- [x] add `patches` subcommand in RUNNING.md https://github.com/flant/addon-operator/issues/8#issuecomment-608415736 (done in #115)
- [x] code spell https://github.com/flant/addon-operator/pull/105
- [x] fix lint errors (done in #116)

**Comment by diafour** [comment]
https://github.com/flant/addon-operator/releases/tag/v1.0.0-beta.6
